condense_wildcard_suffixes = true
fn_single_line = true
format_strings = true
match_block_trailing_comma = true
normalize_comments = true
reorder_imported_names = true
reorder_imports = true
use_try_shorthand = true
where_single_line = true
wrap_comments = true