name: Rust

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout PR
      uses: actions/checkout@v2
    - name: Install benchmarking utilities
      run: cargo install critcmp
    - name: After
      run: git branch && cargo bench -- --noplot --save-baseline after
    - name: Checkout main
      uses: actions/checkout@v2
      with:
        ref: main
    - name: Before
      run: git branch && cargo bench -- --noplot --save-baseline before
    - name: Compare benchmarks
      run: critcmp before after
