name: Benchmark PR

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmark:
    runs-on: ubuntu-latest
    env:
      # A different directory is required so that checkouting out the main
      # branch doesn't affect the PR branch.
      CARGO_TARGET_DIR: /tmp/target
    steps:
    - name: Rust Cache
      uses: Swatinem/rust-cache@v1
    - name: Checkout PR
      uses: actions/checkout@v2
    - name: Install benchmarking utilities
      run: cargo install critcmp
    - name: Benchmark After
      run: git branch && cargo bench -- --noplot --save-baseline after
    - name: Checkout Main
      uses: actions/checkout@v2
      with:
        ref: main
    - name: Benchmark Before
      run: git branch && cargo bench -- --noplot --save-baseline before
    - name: Compare benchmarks
      run: critcmp before after
