name: Rust

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install benchmarking utilities
      run: cargo install critcmp
    - name: After
      run: cargo bench -- --noplot --save-baseline after
    - name: Before
      run: git checkout $(git log --no-decorate --skip 1 | head -n 1 | cut -d ' ' -f2) && cargo bench -- --noplot --save-baseline before
    - name: Compare benchmarks
      run: critcmp before after
