name: Build/Test/Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Rust Cache
        uses: Swatinem/rust-cache@v1
      - name: Build
        run: cargo build --verbose
      - name: Lint
        run: cargo clippy --all-targets --all-features -- -D clippy::all
      - name: Test
        run: cargo test --verbose
  release:
    runs-on: ubuntu-latest
    needs: [test]
    if: contains('refs/heads/main', github.ref)
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Rust Cache
        uses: Swatinem/rust-cache@v1
      - name: Publish
        uses: katyo/publish-crates@v1
        continue-on-error: true
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
