name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set Up Rust Cache
      uses: Swatinem/rust-cache@v1
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Lint
      run: cargo clippy --all-targets --all-features -- -D clippy::all
    - name: Test
      run: cargo test --verbose
